[package]
name = "graph-server-grpc"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
graph = { path = "../../graph" }
graph-store-postgres = { path = "../../store/postgres" }
tonic.workspace = true
tokio.workspace = true
